FROM golang:1.23.0

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY . ./

RUN make build

EXPOSE 8080

# Run
CMD ["/bin/astrid"]
