version: '3.8'

services:
  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: "masterKey"
    restart: always
  master:
    image: chrislusf/seaweedfs:latest
    command: ["master"]
    ports:
      - "9333:9333"  # Expose master server port
    volumes:
      - ./master:/data  # Volume for master data
    restart: unless-stopped

  # Volume Server 1
  volume1:
    image: chrislusf/seaweedfs:latest
    command: ["volume", "-dir", "/data", "-max", "5", "-mserver", "master:9333", "-port", "8080"]
    ports:
      - "8080:8080"  # Expose volume server 1 port
    volumes:
      - ./volume1:/data  # Volume for storing volume server 1 data
    restart: unless-stopped
    depends_on:
      - master

  # Volume Server 2
  volume2:
    image: chrislusf/seaweedfs:latest
    command: ["volume", "-dir", "/data", "-max", "10", "-mserver", "master:9333", "-port", "8081"]
    ports:
      - "8081:8081"  # Expose volume server 2 port
    volumes:
      - ./volume2:/data  # Volume for storing volume server 2 data
    restart: unless-stopped
    depends_on:
      - master
