pipeline {
    agent any
    tools {
        go 'go-1.22.3'
    }
    stages{
        stage('Setup'){
            steps{
                echo 'Pulling Dependencies'
                sh 'make -version'
                sh 'go version'
            }
        }
        stage('Build'){
            steps{ 
                echo 'Building...'
                sh 'make build'
            }
        }
        stage('Test'){
            steps{ 
                echo 'Testing...'
            }
        }
        stage('Deploy'){
            steps{ 
                echo 'Deploying...'
            }
        }
    }
}