pipeline {
    agent any
    tools {
        go 'go-1.22.3'
    }
    stages{
        stage('Setup'){
            steps{
                echo 'Pulling Dependencies'
                sh 'make -version'
                sh 'go version'
                sh 'curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1'
            }
        }
        stage('Build'){
            steps{ 
                echo 'Building...'
                sh 'make build'
            }
        }
        stage('Test'){
            steps{ 
                echo 'Testing...'
                sh 'golangci-lint run'
            }
        }
        stage('Deploy'){
            steps{ 
                echo 'Deploying...'
            }
        }
    }
}